In [1]:
import pandas as pd
from datetime import datetime, timedelta

In [10]:
# Load the CSV file
df = pd.read_csv('news_avg_embs.csv')
df.head()

,id,text,embs
0,61874,The series record a news popularity titled Rep...,"[[0.90625, -1.791015625, -1.1337890625, 0.2349..."
1,61875,The series record a news popularity titled If ...,"[[-0.2401123046875, -1.5810546875, -1.74902343..."
2,61876,The series record a news popularity titled Bar...,"[[0.25732421875, -1.9453125, -0.9931640625, 0...."
3,61877,The series record a news popularity titled Oba...,"[[0.18701171875, -1.8818359375, -0.11480712890..."
4,61878,The series record a news popularity titled Wha...,"[[0.2242431640625, -1.5205078125, -1.252929687..."

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26612 entries, 0 to 26611
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      26612 non-null  int64
 1   text    26612 non-null  object
 2   embs    26612 non-null  object
dtypes: int64(1), object(2)
memory usage: 623.8+ KB

In [11]:
# Define the start date and time interval
start_date = datetime(2015, 11, 1)
time_interval = timedelta(minutes=20)

# Generate timestamps for each row
timestamps = [start_date + i * time_interval for i in range(len(df))]

# Insert the 'Date' column as the first column
df.insert(0, 'Date', timestamps)

# Convert the data from format 'YYYY-MM-DD HH:MM:SS' to 'MM-DD-YYYY'
df['Date'] = pd.to_datetime(df['Date']).dt.strftime('%m-%d-%Y')

df.head()

,Date,id,text,embs
0,11-01-2015,61874,The series record a news popularity titled Rep...,"[[0.90625, -1.791015625, -1.1337890625, 0.2349..."
1,11-01-2015,61875,The series record a news popularity titled If ...,"[[-0.2401123046875, -1.5810546875, -1.74902343..."
2,11-01-2015,61876,The series record a news popularity titled Bar...,"[[0.25732421875, -1.9453125, -0.9931640625, 0...."
3,11-01-2015,61877,The series record a news popularity titled Oba...,"[[0.18701171875, -1.8818359375, -0.11480712890..."
4,11-01-2015,61878,The series record a news popularity titled Wha...,"[[0.2242431640625, -1.5205078125, -1.252929687..."

In [12]:
# Save the modified CSV
df.to_csv('news_avg_embs.csv', index=False)

In [13]:
# check the new csv file
new_df = pd.read_csv('news_avg_embs.csv')
new_df.head()

,Date,id,text,embs
0,11-01-2015,61874,The series record a news popularity titled Rep...,"[[0.90625, -1.791015625, -1.1337890625, 0.2349..."
1,11-01-2015,61875,The series record a news popularity titled If ...,"[[-0.2401123046875, -1.5810546875, -1.74902343..."
2,11-01-2015,61876,The series record a news popularity titled Bar...,"[[0.25732421875, -1.9453125, -0.9931640625, 0...."
3,11-01-2015,61877,The series record a news popularity titled Oba...,"[[0.18701171875, -1.8818359375, -0.11480712890..."
4,11-01-2015,61878,The series record a news popularity titled Wha...,"[[0.2242431640625, -1.5205078125, -1.252929687..."